// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuration.proto

#ifndef PROTOBUF_configuration_2eproto__INCLUDED
#define PROTOBUF_configuration_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace Nous {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_configuration_2eproto();
void protobuf_AssignDesc_configuration_2eproto();
void protobuf_ShutdownFile_configuration_2eproto();

class Configuration;
class Configuration_Ogre;
class Configuration_Ogre_Video;
class Configuration_Ogre_Resource;
class Configuration_Ogre_ResourceGroup;
class Configuration_Ogre_Resources;
class Configuration_Ogre_Plugins;

enum Configuration_Ogre_Video_RenderToTextureMode {
  Configuration_Ogre_Video_RenderToTextureMode_FBO = 0,
  Configuration_Ogre_Video_RenderToTextureMode_PBUFFER = 1
};
bool Configuration_Ogre_Video_RenderToTextureMode_IsValid(int value);
const Configuration_Ogre_Video_RenderToTextureMode Configuration_Ogre_Video_RenderToTextureMode_RenderToTextureMode_MIN = Configuration_Ogre_Video_RenderToTextureMode_FBO;
const Configuration_Ogre_Video_RenderToTextureMode Configuration_Ogre_Video_RenderToTextureMode_RenderToTextureMode_MAX = Configuration_Ogre_Video_RenderToTextureMode_PBUFFER;
const int Configuration_Ogre_Video_RenderToTextureMode_RenderToTextureMode_ARRAYSIZE = Configuration_Ogre_Video_RenderToTextureMode_RenderToTextureMode_MAX + 1;

const ::google::protobuf::EnumDescriptor* Configuration_Ogre_Video_RenderToTextureMode_descriptor();
inline const ::std::string& Configuration_Ogre_Video_RenderToTextureMode_Name(Configuration_Ogre_Video_RenderToTextureMode value) {
  return ::google::protobuf::internal::NameOfEnum(
    Configuration_Ogre_Video_RenderToTextureMode_descriptor(), value);
}
inline bool Configuration_Ogre_Video_RenderToTextureMode_Parse(
    const ::std::string& name, Configuration_Ogre_Video_RenderToTextureMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Configuration_Ogre_Video_RenderToTextureMode>(
    Configuration_Ogre_Video_RenderToTextureMode_descriptor(), name, value);
}
enum Configuration_Ogre_Resource_Type {
  Configuration_Ogre_Resource_Type_FILESYSTEM = 0,
  Configuration_Ogre_Resource_Type_ZIP = 1,
  Configuration_Ogre_Resource_Type_CUSTOM = 2
};
bool Configuration_Ogre_Resource_Type_IsValid(int value);
const Configuration_Ogre_Resource_Type Configuration_Ogre_Resource_Type_Type_MIN = Configuration_Ogre_Resource_Type_FILESYSTEM;
const Configuration_Ogre_Resource_Type Configuration_Ogre_Resource_Type_Type_MAX = Configuration_Ogre_Resource_Type_CUSTOM;
const int Configuration_Ogre_Resource_Type_Type_ARRAYSIZE = Configuration_Ogre_Resource_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Configuration_Ogre_Resource_Type_descriptor();
inline const ::std::string& Configuration_Ogre_Resource_Type_Name(Configuration_Ogre_Resource_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Configuration_Ogre_Resource_Type_descriptor(), value);
}
inline bool Configuration_Ogre_Resource_Type_Parse(
    const ::std::string& name, Configuration_Ogre_Resource_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Configuration_Ogre_Resource_Type>(
    Configuration_Ogre_Resource_Type_descriptor(), name, value);
}
// ===================================================================

class Configuration_Ogre_Video : public ::google::protobuf::Message {
 public:
  Configuration_Ogre_Video();
  virtual ~Configuration_Ogre_Video();
  
  Configuration_Ogre_Video(const Configuration_Ogre_Video& from);
  
  inline Configuration_Ogre_Video& operator=(const Configuration_Ogre_Video& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Configuration_Ogre_Video& default_instance();
  
  void Swap(Configuration_Ogre_Video* other);
  
  // implements Message ----------------------------------------------
  
  Configuration_Ogre_Video* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Configuration_Ogre_Video& from);
  void MergeFrom(const Configuration_Ogre_Video& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Configuration_Ogre_Video_RenderToTextureMode RenderToTextureMode;
  static const RenderToTextureMode FBO = Configuration_Ogre_Video_RenderToTextureMode_FBO;
  static const RenderToTextureMode PBUFFER = Configuration_Ogre_Video_RenderToTextureMode_PBUFFER;
  static inline bool RenderToTextureMode_IsValid(int value) {
    return Configuration_Ogre_Video_RenderToTextureMode_IsValid(value);
  }
  static const RenderToTextureMode RenderToTextureMode_MIN =
    Configuration_Ogre_Video_RenderToTextureMode_RenderToTextureMode_MIN;
  static const RenderToTextureMode RenderToTextureMode_MAX =
    Configuration_Ogre_Video_RenderToTextureMode_RenderToTextureMode_MAX;
  static const int RenderToTextureMode_ARRAYSIZE =
    Configuration_Ogre_Video_RenderToTextureMode_RenderToTextureMode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RenderToTextureMode_descriptor() {
    return Configuration_Ogre_Video_RenderToTextureMode_descriptor();
  }
  static inline const ::std::string& RenderToTextureMode_Name(RenderToTextureMode value) {
    return Configuration_Ogre_Video_RenderToTextureMode_Name(value);
  }
  static inline bool RenderToTextureMode_Parse(const ::std::string& name,
      RenderToTextureMode* value) {
    return Configuration_Ogre_Video_RenderToTextureMode_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required string render_system = 1 [default = "OpenGL Rendering Subsystem"];
  inline bool has_render_system() const;
  inline void clear_render_system();
  static const int kRenderSystemFieldNumber = 1;
  inline const ::std::string& render_system() const;
  inline void set_render_system(const ::std::string& value);
  inline void set_render_system(const char* value);
  inline void set_render_system(const char* value, size_t size);
  inline ::std::string* mutable_render_system();
  
  // required uint32_t frequency = 2 [default = 50];
  inline bool has_frequency() const;
  inline void clear_frequency();
  static const int kFrequencyFieldNumber = 2;
  inline ::google::protobuf::uint32_t frequency() const;
  inline void set_frequency(::google::protobuf::uint32_t value);
  
  // optional uint32_t antialiasing = 3 [default = 0];
  inline bool has_antialiasing() const;
  inline void clear_antialiasing();
  static const int kAntialiasingFieldNumber = 3;
  inline ::google::protobuf::uint32_t antialiasing() const;
  inline void set_antialiasing(::google::protobuf::uint32_t value);
  
  // optional bool fullscreen = 4 [default = false];
  inline bool has_fullscreen() const;
  inline void clear_fullscreen();
  static const int kFullscreenFieldNumber = 4;
  inline bool fullscreen() const;
  inline void set_fullscreen(bool value);
  
  // optional .Nous.Configuration.Ogre.Video.RenderToTextureMode rtt_mode = 5 [default = FBO];
  inline bool has_rtt_mode() const;
  inline void clear_rtt_mode();
  static const int kRttModeFieldNumber = 5;
  inline ::Nous::Configuration_Ogre_Video_RenderToTextureMode rtt_mode() const;
  inline void set_rtt_mode(::Nous::Configuration_Ogre_Video_RenderToTextureMode value);
  
  // optional bool vsync = 6 [default = false];
  inline bool has_vsync() const;
  inline void clear_vsync();
  static const int kVsyncFieldNumber = 6;
  inline bool vsync() const;
  inline void set_vsync(bool value);
  
  // optional uint32_t width = 7 [default = 800];
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 7;
  inline ::google::protobuf::uint32_t width() const;
  inline void set_width(::google::protobuf::uint32_t value);
  
  // optional uint32_t height = 8 [default = 600];
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 8;
  inline ::google::protobuf::uint32_t height() const;
  inline void set_height(::google::protobuf::uint32_t value);
  
  // optional bool srgb_gamma_conversion = 9 [default = false];
  inline bool has_srgb_gamma_conversion() const;
  inline void clear_srgb_gamma_conversion();
  static const int kSrgbGammaConversionFieldNumber = 9;
  inline bool srgb_gamma_conversion() const;
  inline void set_srgb_gamma_conversion(bool value);
  
  // @@protoc_insertion_point(class_scope:Nous.Configuration.Ogre.Video)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* render_system_;
  static const ::std::string _default_render_system_;
  ::google::protobuf::uint32_t frequency_;
  ::google::protobuf::uint32_t antialiasing_;
  bool fullscreen_;
  int rtt_mode_;
  bool vsync_;
  ::google::protobuf::uint32_t width_;
  ::google::protobuf::uint32_t height_;
  bool srgb_gamma_conversion_;
  friend void  protobuf_AddDesc_configuration_2eproto();
  friend void protobuf_AssignDesc_configuration_2eproto();
  friend void protobuf_ShutdownFile_configuration_2eproto();
  
  ::google::protobuf::uint32_t _has_bits_[(9 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Configuration_Ogre_Video* default_instance_;
};
// -------------------------------------------------------------------

class Configuration_Ogre_Resource : public ::google::protobuf::Message {
 public:
  Configuration_Ogre_Resource();
  virtual ~Configuration_Ogre_Resource();
  
  Configuration_Ogre_Resource(const Configuration_Ogre_Resource& from);
  
  inline Configuration_Ogre_Resource& operator=(const Configuration_Ogre_Resource& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Configuration_Ogre_Resource& default_instance();
  
  void Swap(Configuration_Ogre_Resource* other);
  
  // implements Message ----------------------------------------------
  
  Configuration_Ogre_Resource* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Configuration_Ogre_Resource& from);
  void MergeFrom(const Configuration_Ogre_Resource& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Configuration_Ogre_Resource_Type Type;
  static const Type FILESYSTEM = Configuration_Ogre_Resource_Type_FILESYSTEM;
  static const Type ZIP = Configuration_Ogre_Resource_Type_ZIP;
  static const Type CUSTOM = Configuration_Ogre_Resource_Type_CUSTOM;
  static inline bool Type_IsValid(int value) {
    return Configuration_Ogre_Resource_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Configuration_Ogre_Resource_Type_Type_MIN;
  static const Type Type_MAX =
    Configuration_Ogre_Resource_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Configuration_Ogre_Resource_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Configuration_Ogre_Resource_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Configuration_Ogre_Resource_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Configuration_Ogre_Resource_Type_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required .Nous.Configuration.Ogre.Resource.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::Nous::Configuration_Ogre_Resource_Type type() const;
  inline void set_type(::Nous::Configuration_Ogre_Resource_Type value);
  
  // required string path = 2;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 2;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  
  // @@protoc_insertion_point(class_scope:Nous.Configuration.Ogre.Resource)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  int type_;
  ::std::string* path_;
  static const ::std::string _default_path_;
  friend void  protobuf_AddDesc_configuration_2eproto();
  friend void protobuf_AssignDesc_configuration_2eproto();
  friend void protobuf_ShutdownFile_configuration_2eproto();
  
  ::google::protobuf::uint32_t _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Configuration_Ogre_Resource* default_instance_;
};
// -------------------------------------------------------------------

class Configuration_Ogre_ResourceGroup : public ::google::protobuf::Message {
 public:
  Configuration_Ogre_ResourceGroup();
  virtual ~Configuration_Ogre_ResourceGroup();
  
  Configuration_Ogre_ResourceGroup(const Configuration_Ogre_ResourceGroup& from);
  
  inline Configuration_Ogre_ResourceGroup& operator=(const Configuration_Ogre_ResourceGroup& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Configuration_Ogre_ResourceGroup& default_instance();
  
  void Swap(Configuration_Ogre_ResourceGroup* other);
  
  // implements Message ----------------------------------------------
  
  Configuration_Ogre_ResourceGroup* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Configuration_Ogre_ResourceGroup& from);
  void MergeFrom(const Configuration_Ogre_ResourceGroup& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  
  // repeated .Nous.Configuration.Ogre.Resource resource = 2;
  inline int resource_size() const;
  inline void clear_resource();
  static const int kResourceFieldNumber = 2;
  inline const ::Nous::Configuration_Ogre_Resource& resource(int index) const;
  inline ::Nous::Configuration_Ogre_Resource* mutable_resource(int index);
  inline ::Nous::Configuration_Ogre_Resource* add_resource();
  inline const ::google::protobuf::RepeatedPtrField< ::Nous::Configuration_Ogre_Resource >&
      resource() const;
  inline ::google::protobuf::RepeatedPtrField< ::Nous::Configuration_Ogre_Resource >*
      mutable_resource();
  
  // @@protoc_insertion_point(class_scope:Nous.Configuration.Ogre.ResourceGroup)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* name_;
  static const ::std::string _default_name_;
  ::google::protobuf::RepeatedPtrField< ::Nous::Configuration_Ogre_Resource > resource_;
  friend void  protobuf_AddDesc_configuration_2eproto();
  friend void protobuf_AssignDesc_configuration_2eproto();
  friend void protobuf_ShutdownFile_configuration_2eproto();
  
  ::google::protobuf::uint32_t _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Configuration_Ogre_ResourceGroup* default_instance_;
};
// -------------------------------------------------------------------

class Configuration_Ogre_Resources : public ::google::protobuf::Message {
 public:
  Configuration_Ogre_Resources();
  virtual ~Configuration_Ogre_Resources();
  
  Configuration_Ogre_Resources(const Configuration_Ogre_Resources& from);
  
  inline Configuration_Ogre_Resources& operator=(const Configuration_Ogre_Resources& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Configuration_Ogre_Resources& default_instance();
  
  void Swap(Configuration_Ogre_Resources* other);
  
  // implements Message ----------------------------------------------
  
  Configuration_Ogre_Resources* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Configuration_Ogre_Resources& from);
  void MergeFrom(const Configuration_Ogre_Resources& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .Nous.Configuration.Ogre.ResourceGroup group = 1;
  inline int group_size() const;
  inline void clear_group();
  static const int kGroupFieldNumber = 1;
  inline const ::Nous::Configuration_Ogre_ResourceGroup& group(int index) const;
  inline ::Nous::Configuration_Ogre_ResourceGroup* mutable_group(int index);
  inline ::Nous::Configuration_Ogre_ResourceGroup* add_group();
  inline const ::google::protobuf::RepeatedPtrField< ::Nous::Configuration_Ogre_ResourceGroup >&
      group() const;
  inline ::google::protobuf::RepeatedPtrField< ::Nous::Configuration_Ogre_ResourceGroup >*
      mutable_group();
  
  // @@protoc_insertion_point(class_scope:Nous.Configuration.Ogre.Resources)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::Nous::Configuration_Ogre_ResourceGroup > group_;
  friend void  protobuf_AddDesc_configuration_2eproto();
  friend void protobuf_AssignDesc_configuration_2eproto();
  friend void protobuf_ShutdownFile_configuration_2eproto();
  
  ::google::protobuf::uint32_t _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Configuration_Ogre_Resources* default_instance_;
};
// -------------------------------------------------------------------

class Configuration_Ogre_Plugins : public ::google::protobuf::Message {
 public:
  Configuration_Ogre_Plugins();
  virtual ~Configuration_Ogre_Plugins();
  
  Configuration_Ogre_Plugins(const Configuration_Ogre_Plugins& from);
  
  inline Configuration_Ogre_Plugins& operator=(const Configuration_Ogre_Plugins& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Configuration_Ogre_Plugins& default_instance();
  
  void Swap(Configuration_Ogre_Plugins* other);
  
  // implements Message ----------------------------------------------
  
  Configuration_Ogre_Plugins* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Configuration_Ogre_Plugins& from);
  void MergeFrom(const Configuration_Ogre_Plugins& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated string path = 1;
  inline int path_size() const;
  inline void clear_path();
  static const int kPathFieldNumber = 1;
  inline const ::std::string& path(int index) const;
  inline ::std::string* mutable_path(int index);
  inline void set_path(int index, const ::std::string& value);
  inline void set_path(int index, const char* value);
  inline void set_path(int index, const char* value, size_t size);
  inline ::std::string* add_path();
  inline void add_path(const ::std::string& value);
  inline void add_path(const char* value);
  inline void add_path(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& path() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_path();
  
  // repeated string name = 2;
  inline int name_size() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name(int index) const;
  inline ::std::string* mutable_name(int index);
  inline void set_name(int index, const ::std::string& value);
  inline void set_name(int index, const char* value);
  inline void set_name(int index, const char* value, size_t size);
  inline ::std::string* add_name();
  inline void add_name(const ::std::string& value);
  inline void add_name(const char* value);
  inline void add_name(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& name() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_name();
  
  // @@protoc_insertion_point(class_scope:Nous.Configuration.Ogre.Plugins)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::std::string> path_;
  ::google::protobuf::RepeatedPtrField< ::std::string> name_;
  friend void  protobuf_AddDesc_configuration_2eproto();
  friend void protobuf_AssignDesc_configuration_2eproto();
  friend void protobuf_ShutdownFile_configuration_2eproto();
  
  ::google::protobuf::uint32_t _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Configuration_Ogre_Plugins* default_instance_;
};
// -------------------------------------------------------------------

class Configuration_Ogre : public ::google::protobuf::Message {
 public:
  Configuration_Ogre();
  virtual ~Configuration_Ogre();
  
  Configuration_Ogre(const Configuration_Ogre& from);
  
  inline Configuration_Ogre& operator=(const Configuration_Ogre& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Configuration_Ogre& default_instance();
  
  void Swap(Configuration_Ogre* other);
  
  // implements Message ----------------------------------------------
  
  Configuration_Ogre* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Configuration_Ogre& from);
  void MergeFrom(const Configuration_Ogre& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Configuration_Ogre_Video Video;
  typedef Configuration_Ogre_Resource Resource;
  typedef Configuration_Ogre_ResourceGroup ResourceGroup;
  typedef Configuration_Ogre_Resources Resources;
  typedef Configuration_Ogre_Plugins Plugins;
  
  // accessors -------------------------------------------------------
  
  // required .Nous.Configuration.Ogre.Video video = 1;
  inline bool has_video() const;
  inline void clear_video();
  static const int kVideoFieldNumber = 1;
  inline const ::Nous::Configuration_Ogre_Video& video() const;
  inline ::Nous::Configuration_Ogre_Video* mutable_video();
  
  // optional .Nous.Configuration.Ogre.Resources resources = 2;
  inline bool has_resources() const;
  inline void clear_resources();
  static const int kResourcesFieldNumber = 2;
  inline const ::Nous::Configuration_Ogre_Resources& resources() const;
  inline ::Nous::Configuration_Ogre_Resources* mutable_resources();
  
  // optional .Nous.Configuration.Ogre.Plugins plugins = 3;
  inline bool has_plugins() const;
  inline void clear_plugins();
  static const int kPluginsFieldNumber = 3;
  inline const ::Nous::Configuration_Ogre_Plugins& plugins() const;
  inline ::Nous::Configuration_Ogre_Plugins* mutable_plugins();
  
  // @@protoc_insertion_point(class_scope:Nous.Configuration.Ogre)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::Nous::Configuration_Ogre_Video* video_;
  ::Nous::Configuration_Ogre_Resources* resources_;
  ::Nous::Configuration_Ogre_Plugins* plugins_;
  friend void  protobuf_AddDesc_configuration_2eproto();
  friend void protobuf_AssignDesc_configuration_2eproto();
  friend void protobuf_ShutdownFile_configuration_2eproto();
  
  ::google::protobuf::uint32_t _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Configuration_Ogre* default_instance_;
};
// -------------------------------------------------------------------

class Configuration : public ::google::protobuf::Message {
 public:
  Configuration();
  virtual ~Configuration();
  
  Configuration(const Configuration& from);
  
  inline Configuration& operator=(const Configuration& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Configuration& default_instance();
  
  void Swap(Configuration* other);
  
  // implements Message ----------------------------------------------
  
  Configuration* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Configuration& from);
  void MergeFrom(const Configuration& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Configuration_Ogre Ogre;
  
  // accessors -------------------------------------------------------
  
  // optional .Nous.Configuration.Ogre ogre = 1;
  inline bool has_ogre() const;
  inline void clear_ogre();
  static const int kOgreFieldNumber = 1;
  inline const ::Nous::Configuration_Ogre& ogre() const;
  inline ::Nous::Configuration_Ogre* mutable_ogre();
  
  // @@protoc_insertion_point(class_scope:Nous.Configuration)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::Nous::Configuration_Ogre* ogre_;
  friend void  protobuf_AddDesc_configuration_2eproto();
  friend void protobuf_AssignDesc_configuration_2eproto();
  friend void protobuf_ShutdownFile_configuration_2eproto();
  
  ::google::protobuf::uint32_t _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Configuration* default_instance_;
};
// ===================================================================


// ===================================================================

// Configuration_Ogre_Video

// required string render_system = 1 [default = "OpenGL Rendering Subsystem"];
inline bool Configuration_Ogre_Video::has_render_system() const {
  return _has_bit(0);
}
inline void Configuration_Ogre_Video::clear_render_system() {
  if (render_system_ != &_default_render_system_) {
    render_system_->assign(_default_render_system_);
  }
  _clear_bit(0);
}
inline const ::std::string& Configuration_Ogre_Video::render_system() const {
  return *render_system_;
}
inline void Configuration_Ogre_Video::set_render_system(const ::std::string& value) {
  _set_bit(0);
  if (render_system_ == &_default_render_system_) {
    render_system_ = new ::std::string;
  }
  render_system_->assign(value);
}
inline void Configuration_Ogre_Video::set_render_system(const char* value) {
  _set_bit(0);
  if (render_system_ == &_default_render_system_) {
    render_system_ = new ::std::string;
  }
  render_system_->assign(value);
}
inline void Configuration_Ogre_Video::set_render_system(const char* value, size_t size) {
  _set_bit(0);
  if (render_system_ == &_default_render_system_) {
    render_system_ = new ::std::string;
  }
  render_system_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Configuration_Ogre_Video::mutable_render_system() {
  _set_bit(0);
  if (render_system_ == &_default_render_system_) {
    render_system_ = new ::std::string(_default_render_system_);
  }
  return render_system_;
}

// required uint32_t frequency = 2 [default = 50];
inline bool Configuration_Ogre_Video::has_frequency() const {
  return _has_bit(1);
}
inline void Configuration_Ogre_Video::clear_frequency() {
  frequency_ = 50u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32_t Configuration_Ogre_Video::frequency() const {
  return frequency_;
}
inline void Configuration_Ogre_Video::set_frequency(::google::protobuf::uint32_t value) {
  _set_bit(1);
  frequency_ = value;
}

// optional uint32_t antialiasing = 3 [default = 0];
inline bool Configuration_Ogre_Video::has_antialiasing() const {
  return _has_bit(2);
}
inline void Configuration_Ogre_Video::clear_antialiasing() {
  antialiasing_ = 0u;
  _clear_bit(2);
}
inline ::google::protobuf::uint32_t Configuration_Ogre_Video::antialiasing() const {
  return antialiasing_;
}
inline void Configuration_Ogre_Video::set_antialiasing(::google::protobuf::uint32_t value) {
  _set_bit(2);
  antialiasing_ = value;
}

// optional bool fullscreen = 4 [default = false];
inline bool Configuration_Ogre_Video::has_fullscreen() const {
  return _has_bit(3);
}
inline void Configuration_Ogre_Video::clear_fullscreen() {
  fullscreen_ = false;
  _clear_bit(3);
}
inline bool Configuration_Ogre_Video::fullscreen() const {
  return fullscreen_;
}
inline void Configuration_Ogre_Video::set_fullscreen(bool value) {
  _set_bit(3);
  fullscreen_ = value;
}

// optional .Nous.Configuration.Ogre.Video.RenderToTextureMode rtt_mode = 5 [default = FBO];
inline bool Configuration_Ogre_Video::has_rtt_mode() const {
  return _has_bit(4);
}
inline void Configuration_Ogre_Video::clear_rtt_mode() {
  rtt_mode_ = 0;
  _clear_bit(4);
}
inline ::Nous::Configuration_Ogre_Video_RenderToTextureMode Configuration_Ogre_Video::rtt_mode() const {
  return static_cast< ::Nous::Configuration_Ogre_Video_RenderToTextureMode >(rtt_mode_);
}
inline void Configuration_Ogre_Video::set_rtt_mode(::Nous::Configuration_Ogre_Video_RenderToTextureMode value) {
  GOOGLE_DCHECK(::Nous::Configuration_Ogre_Video_RenderToTextureMode_IsValid(value));
  _set_bit(4);
  rtt_mode_ = value;
}

// optional bool vsync = 6 [default = false];
inline bool Configuration_Ogre_Video::has_vsync() const {
  return _has_bit(5);
}
inline void Configuration_Ogre_Video::clear_vsync() {
  vsync_ = false;
  _clear_bit(5);
}
inline bool Configuration_Ogre_Video::vsync() const {
  return vsync_;
}
inline void Configuration_Ogre_Video::set_vsync(bool value) {
  _set_bit(5);
  vsync_ = value;
}

// optional uint32_t width = 7 [default = 800];
inline bool Configuration_Ogre_Video::has_width() const {
  return _has_bit(6);
}
inline void Configuration_Ogre_Video::clear_width() {
  width_ = 800u;
  _clear_bit(6);
}
inline ::google::protobuf::uint32_t Configuration_Ogre_Video::width() const {
  return width_;
}
inline void Configuration_Ogre_Video::set_width(::google::protobuf::uint32_t value) {
  _set_bit(6);
  width_ = value;
}

// optional uint32_t height = 8 [default = 600];
inline bool Configuration_Ogre_Video::has_height() const {
  return _has_bit(7);
}
inline void Configuration_Ogre_Video::clear_height() {
  height_ = 600u;
  _clear_bit(7);
}
inline ::google::protobuf::uint32_t Configuration_Ogre_Video::height() const {
  return height_;
}
inline void Configuration_Ogre_Video::set_height(::google::protobuf::uint32_t value) {
  _set_bit(7);
  height_ = value;
}

// optional bool srgb_gamma_conversion = 9 [default = false];
inline bool Configuration_Ogre_Video::has_srgb_gamma_conversion() const {
  return _has_bit(8);
}
inline void Configuration_Ogre_Video::clear_srgb_gamma_conversion() {
  srgb_gamma_conversion_ = false;
  _clear_bit(8);
}
inline bool Configuration_Ogre_Video::srgb_gamma_conversion() const {
  return srgb_gamma_conversion_;
}
inline void Configuration_Ogre_Video::set_srgb_gamma_conversion(bool value) {
  _set_bit(8);
  srgb_gamma_conversion_ = value;
}

// -------------------------------------------------------------------

// Configuration_Ogre_Resource

// required .Nous.Configuration.Ogre.Resource.Type type = 1;
inline bool Configuration_Ogre_Resource::has_type() const {
  return _has_bit(0);
}
inline void Configuration_Ogre_Resource::clear_type() {
  type_ = 0;
  _clear_bit(0);
}
inline ::Nous::Configuration_Ogre_Resource_Type Configuration_Ogre_Resource::type() const {
  return static_cast< ::Nous::Configuration_Ogre_Resource_Type >(type_);
}
inline void Configuration_Ogre_Resource::set_type(::Nous::Configuration_Ogre_Resource_Type value) {
  GOOGLE_DCHECK(::Nous::Configuration_Ogre_Resource_Type_IsValid(value));
  _set_bit(0);
  type_ = value;
}

// required string path = 2;
inline bool Configuration_Ogre_Resource::has_path() const {
  return _has_bit(1);
}
inline void Configuration_Ogre_Resource::clear_path() {
  if (path_ != &_default_path_) {
    path_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& Configuration_Ogre_Resource::path() const {
  return *path_;
}
inline void Configuration_Ogre_Resource::set_path(const ::std::string& value) {
  _set_bit(1);
  if (path_ == &_default_path_) {
    path_ = new ::std::string;
  }
  path_->assign(value);
}
inline void Configuration_Ogre_Resource::set_path(const char* value) {
  _set_bit(1);
  if (path_ == &_default_path_) {
    path_ = new ::std::string;
  }
  path_->assign(value);
}
inline void Configuration_Ogre_Resource::set_path(const char* value, size_t size) {
  _set_bit(1);
  if (path_ == &_default_path_) {
    path_ = new ::std::string;
  }
  path_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Configuration_Ogre_Resource::mutable_path() {
  _set_bit(1);
  if (path_ == &_default_path_) {
    path_ = new ::std::string;
  }
  return path_;
}

// -------------------------------------------------------------------

// Configuration_Ogre_ResourceGroup

// required string name = 1;
inline bool Configuration_Ogre_ResourceGroup::has_name() const {
  return _has_bit(0);
}
inline void Configuration_Ogre_ResourceGroup::clear_name() {
  if (name_ != &_default_name_) {
    name_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& Configuration_Ogre_ResourceGroup::name() const {
  return *name_;
}
inline void Configuration_Ogre_ResourceGroup::set_name(const ::std::string& value) {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Configuration_Ogre_ResourceGroup::set_name(const char* value) {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Configuration_Ogre_ResourceGroup::set_name(const char* value, size_t size) {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Configuration_Ogre_ResourceGroup::mutable_name() {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  return name_;
}

// repeated .Nous.Configuration.Ogre.Resource resource = 2;
inline int Configuration_Ogre_ResourceGroup::resource_size() const {
  return resource_.size();
}
inline void Configuration_Ogre_ResourceGroup::clear_resource() {
  resource_.Clear();
}
inline const ::Nous::Configuration_Ogre_Resource& Configuration_Ogre_ResourceGroup::resource(int index) const {
  return resource_.Get(index);
}
inline ::Nous::Configuration_Ogre_Resource* Configuration_Ogre_ResourceGroup::mutable_resource(int index) {
  return resource_.Mutable(index);
}
inline ::Nous::Configuration_Ogre_Resource* Configuration_Ogre_ResourceGroup::add_resource() {
  return resource_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Nous::Configuration_Ogre_Resource >&
Configuration_Ogre_ResourceGroup::resource() const {
  return resource_;
}
inline ::google::protobuf::RepeatedPtrField< ::Nous::Configuration_Ogre_Resource >*
Configuration_Ogre_ResourceGroup::mutable_resource() {
  return &resource_;
}

// -------------------------------------------------------------------

// Configuration_Ogre_Resources

// repeated .Nous.Configuration.Ogre.ResourceGroup group = 1;
inline int Configuration_Ogre_Resources::group_size() const {
  return group_.size();
}
inline void Configuration_Ogre_Resources::clear_group() {
  group_.Clear();
}
inline const ::Nous::Configuration_Ogre_ResourceGroup& Configuration_Ogre_Resources::group(int index) const {
  return group_.Get(index);
}
inline ::Nous::Configuration_Ogre_ResourceGroup* Configuration_Ogre_Resources::mutable_group(int index) {
  return group_.Mutable(index);
}
inline ::Nous::Configuration_Ogre_ResourceGroup* Configuration_Ogre_Resources::add_group() {
  return group_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Nous::Configuration_Ogre_ResourceGroup >&
Configuration_Ogre_Resources::group() const {
  return group_;
}
inline ::google::protobuf::RepeatedPtrField< ::Nous::Configuration_Ogre_ResourceGroup >*
Configuration_Ogre_Resources::mutable_group() {
  return &group_;
}

// -------------------------------------------------------------------

// Configuration_Ogre_Plugins

// repeated string path = 1;
inline int Configuration_Ogre_Plugins::path_size() const {
  return path_.size();
}
inline void Configuration_Ogre_Plugins::clear_path() {
  path_.Clear();
}
inline const ::std::string& Configuration_Ogre_Plugins::path(int index) const {
  return path_.Get(index);
}
inline ::std::string* Configuration_Ogre_Plugins::mutable_path(int index) {
  return path_.Mutable(index);
}
inline void Configuration_Ogre_Plugins::set_path(int index, const ::std::string& value) {
  path_.Mutable(index)->assign(value);
}
inline void Configuration_Ogre_Plugins::set_path(int index, const char* value) {
  path_.Mutable(index)->assign(value);
}
inline void Configuration_Ogre_Plugins::set_path(int index, const char* value, size_t size) {
  path_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Configuration_Ogre_Plugins::add_path() {
  return path_.Add();
}
inline void Configuration_Ogre_Plugins::add_path(const ::std::string& value) {
  path_.Add()->assign(value);
}
inline void Configuration_Ogre_Plugins::add_path(const char* value) {
  path_.Add()->assign(value);
}
inline void Configuration_Ogre_Plugins::add_path(const char* value, size_t size) {
  path_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Configuration_Ogre_Plugins::path() const {
  return path_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Configuration_Ogre_Plugins::mutable_path() {
  return &path_;
}

// repeated string name = 2;
inline int Configuration_Ogre_Plugins::name_size() const {
  return name_.size();
}
inline void Configuration_Ogre_Plugins::clear_name() {
  name_.Clear();
}
inline const ::std::string& Configuration_Ogre_Plugins::name(int index) const {
  return name_.Get(index);
}
inline ::std::string* Configuration_Ogre_Plugins::mutable_name(int index) {
  return name_.Mutable(index);
}
inline void Configuration_Ogre_Plugins::set_name(int index, const ::std::string& value) {
  name_.Mutable(index)->assign(value);
}
inline void Configuration_Ogre_Plugins::set_name(int index, const char* value) {
  name_.Mutable(index)->assign(value);
}
inline void Configuration_Ogre_Plugins::set_name(int index, const char* value, size_t size) {
  name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Configuration_Ogre_Plugins::add_name() {
  return name_.Add();
}
inline void Configuration_Ogre_Plugins::add_name(const ::std::string& value) {
  name_.Add()->assign(value);
}
inline void Configuration_Ogre_Plugins::add_name(const char* value) {
  name_.Add()->assign(value);
}
inline void Configuration_Ogre_Plugins::add_name(const char* value, size_t size) {
  name_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Configuration_Ogre_Plugins::name() const {
  return name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Configuration_Ogre_Plugins::mutable_name() {
  return &name_;
}

// -------------------------------------------------------------------

// Configuration_Ogre

// required .Nous.Configuration.Ogre.Video video = 1;
inline bool Configuration_Ogre::has_video() const {
  return _has_bit(0);
}
inline void Configuration_Ogre::clear_video() {
  if (video_ != NULL) video_->::Nous::Configuration_Ogre_Video::Clear();
  _clear_bit(0);
}
inline const ::Nous::Configuration_Ogre_Video& Configuration_Ogre::video() const {
  return video_ != NULL ? *video_ : *default_instance_->video_;
}
inline ::Nous::Configuration_Ogre_Video* Configuration_Ogre::mutable_video() {
  _set_bit(0);
  if (video_ == NULL) video_ = new ::Nous::Configuration_Ogre_Video;
  return video_;
}

// optional .Nous.Configuration.Ogre.Resources resources = 2;
inline bool Configuration_Ogre::has_resources() const {
  return _has_bit(1);
}
inline void Configuration_Ogre::clear_resources() {
  if (resources_ != NULL) resources_->::Nous::Configuration_Ogre_Resources::Clear();
  _clear_bit(1);
}
inline const ::Nous::Configuration_Ogre_Resources& Configuration_Ogre::resources() const {
  return resources_ != NULL ? *resources_ : *default_instance_->resources_;
}
inline ::Nous::Configuration_Ogre_Resources* Configuration_Ogre::mutable_resources() {
  _set_bit(1);
  if (resources_ == NULL) resources_ = new ::Nous::Configuration_Ogre_Resources;
  return resources_;
}

// optional .Nous.Configuration.Ogre.Plugins plugins = 3;
inline bool Configuration_Ogre::has_plugins() const {
  return _has_bit(2);
}
inline void Configuration_Ogre::clear_plugins() {
  if (plugins_ != NULL) plugins_->::Nous::Configuration_Ogre_Plugins::Clear();
  _clear_bit(2);
}
inline const ::Nous::Configuration_Ogre_Plugins& Configuration_Ogre::plugins() const {
  return plugins_ != NULL ? *plugins_ : *default_instance_->plugins_;
}
inline ::Nous::Configuration_Ogre_Plugins* Configuration_Ogre::mutable_plugins() {
  _set_bit(2);
  if (plugins_ == NULL) plugins_ = new ::Nous::Configuration_Ogre_Plugins;
  return plugins_;
}

// -------------------------------------------------------------------

// Configuration

// optional .Nous.Configuration.Ogre ogre = 1;
inline bool Configuration::has_ogre() const {
  return _has_bit(0);
}
inline void Configuration::clear_ogre() {
  if (ogre_ != NULL) ogre_->::Nous::Configuration_Ogre::Clear();
  _clear_bit(0);
}
inline const ::Nous::Configuration_Ogre& Configuration::ogre() const {
  return ogre_ != NULL ? *ogre_ : *default_instance_->ogre_;
}
inline ::Nous::Configuration_Ogre* Configuration::mutable_ogre() {
  _set_bit(0);
  if (ogre_ == NULL) ogre_ = new ::Nous::Configuration_Ogre;
  return ogre_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Nous

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Nous::Configuration_Ogre_Video_RenderToTextureMode>() {
  return ::Nous::Configuration_Ogre_Video_RenderToTextureMode_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Nous::Configuration_Ogre_Resource_Type>() {
  return ::Nous::Configuration_Ogre_Resource_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_configuration_2eproto__INCLUDED
